server:
  port: 8080

spring:
  application:
    name: search-engine
  datasource:
    username: admin
    password: admin
#    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:postgresql://localhost:5432/search_engine
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
indexing-settings:
  sites:
    - url: http://www.playback.ru/
      name: PlayBack.Ru
    - url: https://volochek.life/
      name: Volochek Life