version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: search_engine
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"